---
name: CreativeWorld
main: yutarou\cw
api:
  - 3.0.0
  - 4.0.0
version: 1.0.0
author: yutarou1241477
description: クリエイティブワールドにテレポートします
commands:
  cw:
    description: "§l[CreativeWorld]クリエイティブワールドへ"
    usage: "/cw"
  cw_reload:
    description: "§l[CreativeWorld]Configのリロード"
    usage: "/cw_reload"
    permission: cw.op
permissions:
  cw.op:
    default: op
...
